# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/COD_Projects/LABH5/LABH5.srcs/sources_1/ip/dist_mem_reginfo/dist_mem_reginfo.xci
# IP: The module: 'dist_mem_reginfo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/COD_Projects/LABH5/LABH5.gen/sources_1/ip/dist_mem_reginfo/dist_mem_reginfo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_reginfo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/COD_Projects/LABH5/LABH5.srcs/sources_1/ip/dist_mem_reginfo/dist_mem_reginfo.xci
# IP: The module: 'dist_mem_reginfo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/COD_Projects/LABH5/LABH5.gen/sources_1/ip/dist_mem_reginfo/dist_mem_reginfo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_reginfo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
