# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/COD_Projects/LABH4/LABH4.srcs/sources_1/ip/inst_mem/inst_mem.xci
# IP: The module: 'inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/COD_Projects/LABH4/LABH4.gen/sources_1/ip/inst_mem/inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/COD_Projects/LABH4/LABH4.srcs/sources_1/ip/inst_mem/inst_mem.xci
# IP: The module: 'inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/COD_Projects/LABH4/LABH4.gen/sources_1/ip/inst_mem/inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
