# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/COD_Projects/LABH6/LABH6.runs/synth_1/MAIN.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param chipscope.maxJobs 5
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/COD_Projects/LABH6/LABH6.cache/wt [current_project]
set_property parent.project_path D:/COD_Projects/LABH6/LABH6.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/COD_Projects/LABH6/LABH6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/COD_Projects/LABH6/testcases/IR_sort_for_cpu.coe
add_files d:/COD_Projects/LABH6/testcases/IR_sort_1000.coe
read_verilog -library xil_defaultlib {
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/ALU.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/ALUA_Gen.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/ALUB_Gen.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Branch_Cond.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/CPU.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Control.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/DB.v
  D:/COD_Projects/LABH6/SDU_PL-v2_wzc/DCP.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/DataMem.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Dcache.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Decode.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/EXMEM.v
  D:/COD_Projects/LABH6/SDU_PL-v2_wzc/FD.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Forward.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Hazard.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/IDEX.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/IFID.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/IOU.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Imm_Gen.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Instr_Mem.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/MEMWB.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/MUX_2_1.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/MUX_3_1.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Mem_sdu.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/PC.v
  D:/COD_Projects/LABH6/SDU_PL-v2_wzc/PRINT.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/PS.v
  D:/COD_Projects/LABH6/SDU_PL-v2_wzc/ROM.v
  D:/COD_Projects/LABH6/SDU_PL-v2_wzc/RX.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/Registers.v
  D:/COD_Projects/LABH6/SDU_PL-v2_wzc/SCAN.v
  D:/COD_Projects/LABH6/SDU_PL-v2_wzc/SDU.v
  D:/COD_Projects/LABH6/SDU_PL-v2_wzc/TX.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/mem_and_mmio.v
  D:/COD_Projects/LABH6/LABH6.srcs/sources_1/new/npc_Gen.v
  D:/COD_Projects/LABH6/SDU_PL-v2_wzc/MAIN.v
}
read_ip -quiet D:/COD_Projects/LABH6/LABH6.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/COD_Projects/LABH6/LABH6.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/COD_Projects/LABH6/LABH6.srcs/sources_1/ip/instr_mem/instr_mem.xci
set_property used_in_implementation false [get_files -all d:/COD_Projects/LABH6/LABH6.gen/sources_1/ip/instr_mem/instr_mem_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/COD_Projects/LABH6/LABH6.srcs/constrs_1/new/LABH6_xdc.xdc
set_property used_in_implementation false [get_files D:/COD_Projects/LABH6/LABH6.srcs/constrs_1/new/LABH6_xdc.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/COD_Projects/LABH6/LABH6.srcs/utils_1/imports/synth_1/Top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top MAIN -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MAIN.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MAIN_utilization_synth.rpt -pb MAIN_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
